// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AcceptInviteResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Team    *Team  `json:"team,omitempty"`
}

type Conversation struct {
	ID            uuid.UUID `json:"id"`
	TeamID        uuid.UUID `json:"teamId"`
	Kind          string    `json:"kind"`
	Peer          *User     `json:"peer,omitempty"`
	LastMessage   *Message  `json:"lastMessage,omitempty"`
	LastMessageAt time.Time `json:"lastMessageAt"`
	UnreadCount   int32     `json:"unreadCount"`
}

type CreateAccountInput struct {
	Phone           string  `json:"phone"`
	FirstName       string  `json:"firstName"`
	Surname         string  `json:"surname"`
	OtherNames      *string `json:"otherNames,omitempty"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirmPassword"`
}

type CreateAccountResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	User    *User  `json:"user,omitempty"`
}

type CreateGoalInput struct {
	Title       string      `json:"title"`
	Description *string     `json:"description,omitempty"`
	Status      *GoalStatus `json:"status,omitempty"`
	DueAt       *time.Time  `json:"dueAt,omitempty"`
	OwnerID     *uuid.UUID  `json:"ownerId,omitempty"`
}

type CreateTaskInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Priority    *Priority  `json:"priority,omitempty"`
	DueAt       *time.Time `json:"dueAt,omitempty"`
	AssigneeID  *uuid.UUID `json:"assigneeId,omitempty"`
}

type Dashboard struct {
	Stats           *DashboardStats      `json:"stats"`
	CompletedToday  int32                `json:"completedToday"`
	UpcomingTasks   []*Task              `json:"upcomingTasks"`
	StatusBreakdown []*DashboardSlice    `json:"statusBreakdown"`
	Activity        []*DashboardActivity `json:"activity"`
	DueThisWeek     []*DashboardDay      `json:"dueThisWeek"`
}

type DashboardActivity struct {
	ID        uuid.UUID `json:"id"`
	Kind      string    `json:"kind"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
}

type DashboardDay struct {
	Day   string `json:"day"`
	Label string `json:"label"`
	Count int32  `json:"count"`
}

type DashboardSlice struct {
	Key     string `json:"key"`
	Label   string `json:"label"`
	Count   int32  `json:"count"`
	Percent int32  `json:"percent"`
}

type DashboardStats struct {
	DoneToday         int32 `json:"doneToday"`
	InProgress        int32 `json:"inProgress"`
	Overdue           int32 `json:"overdue"`
	CompletedThisWeek int32 `json:"completedThisWeek"`
}

type Goal struct {
	ID          uuid.UUID    `json:"id"`
	TeamID      uuid.UUID    `json:"teamId"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      GoalStatus   `json:"status"`
	DueAt       *time.Time   `json:"dueAt,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	Owner       *User        `json:"owner"`
	Progress    int32        `json:"progress"`
	KeyResults  []*KeyResult `json:"keyResults"`
}

type GoalResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Goal    *Goal  `json:"goal,omitempty"`
}

type Invite struct {
	ID        uuid.UUID `json:"id"`
	TeamName  string    `json:"teamName"`
	Phone     string    `json:"phone"`
	Role      Role      `json:"role"`
	Status    string    `json:"status"`
	InvitedBy *User     `json:"invitedBy"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type InviteResult struct {
	Success           bool    `json:"success"`
	Message           string  `json:"message"`
	Invite            *Invite `json:"invite,omitempty"`
	InviteeRegistered bool    `json:"inviteeRegistered"`
	AlreadyMember     bool    `json:"alreadyMember"`
}

type KeyResult struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Progress  int32     `json:"progress"`
	CreatedAt time.Time `json:"createdAt"`
}

type LoginResult struct {
	Success      bool    `json:"success"`
	Message      string  `json:"message"`
	User         *User   `json:"user,omitempty"`
	AccessToken  *string `json:"accessToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type Message struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversationId"`
	Sender         *User     `json:"sender"`
	Body           string    `json:"body"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Notification struct {
	ID        uuid.UUID  `json:"id"`
	Kind      string     `json:"kind"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	TaskID    *uuid.UUID `json:"taskId,omitempty"`
	Read      bool       `json:"read"`
	CreatedAt time.Time  `json:"createdAt"`
}

type OTPResult struct {
	Success           bool   `json:"success"`
	Message           string `json:"message"`
	ExpiresInSeconds  *int32 `json:"expiresInSeconds,omitempty"`
	RetryAfterSeconds *int32 `json:"retryAfterSeconds,omitempty"`
}

type Query struct {
}

type RefreshResult struct {
	Success      bool    `json:"success"`
	Message      string  `json:"message"`
	User         *User   `json:"user,omitempty"`
	AccessToken  *string `json:"accessToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type ResetPasswordResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Task struct {
	ID          uuid.UUID  `json:"id"`
	TeamID      uuid.UUID  `json:"teamId"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Status      TaskStatus `json:"status"`
	Priority    Priority   `json:"priority"`
	DueAt       *time.Time `json:"dueAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	CreatedBy   *User      `json:"createdBy"`
	Assignee    *User      `json:"assignee,omitempty"`
}

type TaskResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Task    *Task  `json:"task,omitempty"`
}

type Team struct {
	ID      uuid.UUID     `json:"id"`
	Name    string        `json:"name"`
	Role    Role          `json:"role"`
	Members []*TeamMember `json:"members"`
	Invites []*Invite     `json:"invites"`
}

type TeamMember struct {
	ID        uuid.UUID `json:"id"`
	Phone     string    `json:"phone"`
	FirstName string    `json:"firstName"`
	Surname   string    `json:"surname"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type UpdateTaskInput struct {
	Title       *string     `json:"title,omitempty"`
	Description *string     `json:"description,omitempty"`
	Priority    *Priority   `json:"priority,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	AssigneeID  *uuid.UUID  `json:"assigneeId,omitempty"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Phone      string    `json:"phone"`
	FirstName  string    `json:"firstName"`
	Surname    string    `json:"surname"`
	OtherNames *string   `json:"otherNames,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type VerifyOTPResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GoalStatus string

const (
	GoalStatusOnTrack GoalStatus = "ON_TRACK"
	GoalStatusAtRisk  GoalStatus = "AT_RISK"
	GoalStatusBehind  GoalStatus = "BEHIND"
	GoalStatusDone    GoalStatus = "DONE"
)

var AllGoalStatus = []GoalStatus{
	GoalStatusOnTrack,
	GoalStatusAtRisk,
	GoalStatusBehind,
	GoalStatusDone,
}

func (e GoalStatus) IsValid() bool {
	switch e {
	case GoalStatusOnTrack, GoalStatusAtRisk, GoalStatusBehind, GoalStatusDone:
		return true
	}
	return false
}

func (e GoalStatus) String() string {
	return string(e)
}

func (e *GoalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GoalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GoalStatus", str)
	}
	return nil
}

func (e GoalStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GoalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GoalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Priority string

const (
	PriorityLow    Priority = "LOW"
	PriorityMedium Priority = "MEDIUM"
	PriorityHigh   Priority = "HIGH"
)

var AllPriority = []Priority{
	PriorityLow,
	PriorityMedium,
	PriorityHigh,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityLow, PriorityMedium, PriorityHigh:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Priority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Priority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleMember Role = "MEMBER"
	RoleGuest  Role = "GUEST"
)

var AllRole = []Role{
	RoleAdmin,
	RoleMember,
	RoleGuest,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleMember, RoleGuest:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "TODO"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusReview     TaskStatus = "REVIEW"
	TaskStatusDone       TaskStatus = "DONE"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusTodo,
	TaskStatusInProgress,
	TaskStatusReview,
	TaskStatusDone,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusTodo, TaskStatusInProgress, TaskStatusReview, TaskStatusDone:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
