// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AcceptInviteResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Team    *Team  `json:"team,omitempty"`
}

type CreateAccountInput struct {
	Phone           string  `json:"phone"`
	FirstName       string  `json:"firstName"`
	Surname         string  `json:"surname"`
	OtherNames      *string `json:"otherNames,omitempty"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirmPassword"`
}

type CreateAccountResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	User    *User  `json:"user,omitempty"`
}

type CreateTaskInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Priority    *Priority  `json:"priority,omitempty"`
	DueAt       *time.Time `json:"dueAt,omitempty"`
	AssigneeID  *uuid.UUID `json:"assigneeId,omitempty"`
}

type Invite struct {
	ID        uuid.UUID `json:"id"`
	TeamName  string    `json:"teamName"`
	Phone     string    `json:"phone"`
	Role      Role      `json:"role"`
	Status    string    `json:"status"`
	InvitedBy *User     `json:"invitedBy"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type InviteResult struct {
	Success           bool    `json:"success"`
	Message           string  `json:"message"`
	Invite            *Invite `json:"invite,omitempty"`
	InviteeRegistered bool    `json:"inviteeRegistered"`
	AlreadyMember     bool    `json:"alreadyMember"`
}

type LoginResult struct {
	Success      bool    `json:"success"`
	Message      string  `json:"message"`
	User         *User   `json:"user,omitempty"`
	AccessToken  *string `json:"accessToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID        uuid.UUID  `json:"id"`
	Kind      string     `json:"kind"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	TaskID    *uuid.UUID `json:"taskId,omitempty"`
	Read      bool       `json:"read"`
	CreatedAt time.Time  `json:"createdAt"`
}

type OTPResult struct {
	Success           bool   `json:"success"`
	Message           string `json:"message"`
	ExpiresInSeconds  *int32 `json:"expiresInSeconds,omitempty"`
	RetryAfterSeconds *int32 `json:"retryAfterSeconds,omitempty"`
}

type Query struct {
}

type RefreshResult struct {
	Success      bool    `json:"success"`
	Message      string  `json:"message"`
	User         *User   `json:"user,omitempty"`
	AccessToken  *string `json:"accessToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

type ResetPasswordResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Task struct {
	ID          uuid.UUID  `json:"id"`
	TeamID      uuid.UUID  `json:"teamId"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Status      TaskStatus `json:"status"`
	Priority    Priority   `json:"priority"`
	DueAt       *time.Time `json:"dueAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	CreatedBy   *User      `json:"createdBy"`
	Assignee    *User      `json:"assignee,omitempty"`
}

type TaskResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Task    *Task  `json:"task,omitempty"`
}

type Team struct {
	ID      uuid.UUID     `json:"id"`
	Name    string        `json:"name"`
	Role    Role          `json:"role"`
	Members []*TeamMember `json:"members"`
	Invites []*Invite     `json:"invites"`
}

type TeamMember struct {
	ID        uuid.UUID `json:"id"`
	Phone     string    `json:"phone"`
	FirstName string    `json:"firstName"`
	Surname   string    `json:"surname"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Phone      string    `json:"phone"`
	FirstName  string    `json:"firstName"`
	Surname    string    `json:"surname"`
	OtherNames *string   `json:"otherNames,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type VerifyOTPResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Priority string

const (
	PriorityLow    Priority = "LOW"
	PriorityMedium Priority = "MEDIUM"
	PriorityHigh   Priority = "HIGH"
)

var AllPriority = []Priority{
	PriorityLow,
	PriorityMedium,
	PriorityHigh,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityLow, PriorityMedium, PriorityHigh:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Priority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Priority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleMember Role = "MEMBER"
	RoleGuest  Role = "GUEST"
)

var AllRole = []Role{
	RoleAdmin,
	RoleMember,
	RoleGuest,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleMember, RoleGuest:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "TODO"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusReview     TaskStatus = "REVIEW"
	TaskStatusDone       TaskStatus = "DONE"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusTodo,
	TaskStatusInProgress,
	TaskStatusReview,
	TaskStatusDone,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusTodo, TaskStatusInProgress, TaskStatusReview, TaskStatusDone:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
