// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type CreateAccountInput struct {
	Phone           string  `json:"phone"`
	FirstName       string  `json:"firstName"`
	Surname         string  `json:"surname"`
	OtherNames      *string `json:"otherNames,omitempty"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirmPassword"`
}

type CreateAccountResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	User    *User  `json:"user,omitempty"`
}

type Mutation struct {
}

type OTPResult struct {
	Success           bool   `json:"success"`
	Message           string `json:"message"`
	ExpiresInSeconds  *int32 `json:"expiresInSeconds,omitempty"`
	RetryAfterSeconds *int32 `json:"retryAfterSeconds,omitempty"`
}

type Query struct {
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Phone      string    `json:"phone"`
	FirstName  string    `json:"firstName"`
	Surname    string    `json:"surname"`
	OtherNames *string   `json:"otherNames,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type VerifyOTPResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
