package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"time"

	"taskmanager/graph/model"
	"taskmanager/internal/db"
	"taskmanager/internal/notif"
	"taskmanager/internal/otp"
	"taskmanager/internal/validator"

	"golang.org/x/crypto/bcrypt"
)

// RequestOtp is the resolver for the requestOTP field.
func (r *mutationResolver) RequestOtp(ctx context.Context, phone string) (*model.OTPResult, error) {
	normalized, err := validator.NormalizeGhanaPhone(phone)
	if err != nil {
		return nil, err
	}

	registered, err := db.PhoneRegistered(ctx, r.Pool, normalized)
	if err != nil {
		return nil, fmt.Errorf("check phone registered: %w", err)
	}
	if registered {
		return &model.OTPResult{
			Success: false,
			Message: "an account with this phone number already exists",
		}, nil
	}

	lastOTP, ok, err := db.LatestOTPTime(ctx, r.Pool, normalized, otpPurposeRegister)
	if err == nil && ok && time.Since(lastOTP) < otp.ResendMinPeriod {
		retryAfter := int(time.Until(lastOTP.Add(otp.ResendMinPeriod)).Seconds())
		if retryAfter < 1 {
			retryAfter = 1
		}
		return &model.OTPResult{
			Success:           false,
			Message:           "please wait before requesting another code",
			RetryAfterSeconds: int32Ptr(int32(retryAfter)),
		}, nil
	}

	code, codeHash, err := otp.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate otp: %w", err)
	}

	expiresAt := time.Now().Add(otp.DefaultTTL)
	if _, err := db.RequestOTP(ctx, r.Pool, normalized, otpPurposeRegister, codeHash, expiresAt); err != nil {
		return nil, fmt.Errorf("store otp: %w", err)
	}

	if !r.SMSQueue.Enqueue(notif.SMSPayload{
		PhoneNumbers: []string{normalized},
		Message:      otp.Message(code, otp.DefaultTTL),
	}, "") {
		return &model.OTPResult{
			Success: false,
			Message: "temporarily unable to send the verification code, please try again",
		}, nil
	}

	return &model.OTPResult{
		Success:          true,
		Message:          "verification code sent",
		ExpiresInSeconds: int32Ptr(int32(otp.DefaultTTL.Seconds())),
	}, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, phone string, code string) (*model.VerifyOTPResult, error) {
	normalized, err := validator.NormalizeGhanaPhone(phone)
	if err != nil {
		return nil, err
	}

	valid, reason, err := db.VerifyOTP(ctx, r.Pool, normalized, otpPurposeRegister, code)
	if err != nil {
		return nil, fmt.Errorf("verify otp: %w", err)
	}

	if !valid {
		return &model.VerifyOTPResult{Success: false, Message: otpFailureMessage(reason)}, nil
	}

	return &model.VerifyOTPResult{Success: true, Message: "verification successful"}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.CreateAccountResult, error) {
	normalized, err := validator.NormalizeGhanaPhone(input.Phone)
	if err != nil {
		return nil, err
	}

	if err := validator.ValidateName(input.FirstName, "first name"); err != nil {
		return nil, err
	}
	if err := validator.ValidateName(input.Surname, "surname"); err != nil {
		return nil, err
	}
	if input.OtherNames != nil {
		if err := validator.ValidateName(*input.OtherNames, "other names"); err != nil {
			return nil, err
		}
	}

	if err := validator.ValidatePassword(input.Password); err != nil {
		return nil, err
	}
	if err := validator.ValidatePasswordConfirmation(input.Password, input.ConfirmPassword); err != nil {
		return nil, err
	}

	passwordHash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("hash password: %w", err)
	}

	var otherNames string
	if input.OtherNames != nil {
		otherNames = *input.OtherNames
	}

	user, err := db.CreateUser(
		ctx, r.Pool,
		normalized, input.FirstName, input.Surname, otherNames, string(passwordHash),
	)
	if err != nil {
		if errors.Is(err, db.ErrPhoneNotVerified) {
			return &model.CreateAccountResult{
				Success: false,
				Message: "phone number must be verified first",
			}, nil
		}
		if errors.Is(err, db.ErrPhoneAlreadyRegistered) {
			return &model.CreateAccountResult{
				Success: false,
				Message: "an account with this phone number already exists",
			}, nil
		}
		return nil, fmt.Errorf("create user: %w", err)
	}

	return &model.CreateAccountResult{
		Success: true,
		Message: "account created",
		User:    toModelUser(user),
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

const otpPurposeRegister = "register"