package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"taskmanager/graph/model"
	"taskmanager/internal/auth"
	"taskmanager/internal/db"
	"taskmanager/internal/otp"
	"taskmanager/internal/validator"
	"taskmanager/types"
	"time"

	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"
)

// RequestOtp is the resolver for the requestOTP field.
func (r *mutationResolver) RequestOtp(ctx context.Context, phone string) (*model.OTPResult, error) {
	normalized, err := validator.NormalizePhone(phone)
	if err != nil {
		return nil, err
	}
	if err := r.guardAuth(ctx, normalized); err != nil {
		return nil, err
	}

	registered, err := db.PhoneRegistered(ctx, r.Pool, normalized)
	if err != nil {
		return nil, fmt.Errorf("check phone registered: %w", err)
	}
	if registered {
		return &model.OTPResult{
			Success: false,
			Message: "an account with this phone number already exists",
		}, nil
	}

	lastOTP, ok, err := db.LatestOTPTime(ctx, r.Pool, normalized, otpPurposeRegister)
	if err == nil && ok && time.Since(lastOTP) < otp.ResendMinPeriod {
		retryAfter := int(time.Until(lastOTP.Add(otp.ResendMinPeriod)).Seconds())
		if retryAfter < 1 {
			retryAfter = 1
		}
		return &model.OTPResult{
			Success:           false,
			Message:           "please wait before requesting another code",
			RetryAfterSeconds: int32Ptr(int32(retryAfter)),
		}, nil
	}

	code, codeHash, err := otp.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate otp: %w", err)
	}

	expiresAt := time.Now().Add(otp.DefaultTTL)
	if _, err := db.RequestOTP(ctx, r.Pool, normalized, otpPurposeRegister, codeHash, expiresAt); err != nil {
		return nil, fmt.Errorf("store otp: %w", err)
	}

	if !r.SMSQueue.Enqueue(types.SMSPayload{
		PhoneNumbers: []string{normalized},
		Message:      otp.Message(code, otp.DefaultTTL),
	}, "") {
		return &model.OTPResult{
			Success: false,
			Message: "temporarily unable to send the verification code, please try again",
		}, nil
	}

	return &model.OTPResult{
		Success:          true,
		Message:          "verification code sent",
		ExpiresInSeconds: int32Ptr(int32(otp.DefaultTTL.Seconds())),
	}, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, phone string, code string) (*model.VerifyOTPResult, error) {
	normalized, err := validator.NormalizePhone(phone)
	if err != nil {
		return nil, err
	}
	if err := r.guardAuth(ctx, normalized); err != nil {
		return nil, err
	}

	valid, reason, err := db.VerifyOTP(ctx, r.Pool, normalized, otpPurposeRegister, code)
	if err != nil {
		return nil, fmt.Errorf("verify otp: %w", err)
	}

	if !valid {
		return &model.VerifyOTPResult{Success: false, Message: otpFailureMessage(reason)}, nil
	}

	return &model.VerifyOTPResult{Success: true, Message: "verification successful"}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.CreateAccountResult, error) {
	normalized, err := validator.NormalizePhone(input.Phone)
	if err != nil {
		return nil, err
	}

	if err := validator.ValidateName(input.FirstName, "first name"); err != nil {
		return nil, err
	}
	if err := validator.ValidateName(input.Surname, "surname"); err != nil {
		return nil, err
	}
	if input.OtherNames != nil {
		if err := validator.ValidateName(*input.OtherNames, "other names"); err != nil {
			return nil, err
		}
	}

	if err := validator.ValidatePassword(input.Password); err != nil {
		return nil, err
	}
	if err := validator.ValidatePasswordConfirmation(input.Password, input.ConfirmPassword); err != nil {
		return nil, err
	}

	passwordHash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("hash password: %w", err)
	}

	var otherNames string
	if input.OtherNames != nil {
		otherNames = *input.OtherNames
	}

	user, err := db.CreateUser(
		ctx, r.Pool,
		normalized, input.FirstName, input.Surname, otherNames, string(passwordHash),
	)
	if err != nil {
		if errors.Is(err, db.ErrPhoneNotVerified) {
			return &model.CreateAccountResult{
				Success: false,
				Message: "phone number must be verified first",
			}, nil
		}
		if errors.Is(err, db.ErrPhoneAlreadyRegistered) {
			return &model.CreateAccountResult{
				Success: false,
				Message: "an account with this phone number already exists",
			}, nil
		}
		return nil, fmt.Errorf("create user: %w", err)
	}

	return &model.CreateAccountResult{
		Success: true,
		Message: "account created",
		User:    toModelUser(user),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, phone string, password string) (*model.LoginResult, error) {
	normalized, err := validator.NormalizePhone(phone)
	if err != nil {
		return nil, err
	}
	if err := r.guardAuth(ctx, normalized); err != nil {
		return nil, err
	}

	creds, err := db.UserByPhone(ctx, r.Pool, normalized)
	if err != nil {
		if errors.Is(err, db.ErrUserNotFound) {
			return &model.LoginResult{
				Success: false,
				Message: "invalid phone number or password",
			}, nil
		}
		return nil, fmt.Errorf("load user: %w", err)
	}

	if bcrypt.CompareHashAndPassword([]byte(creds.PasswordHash), []byte(password)) != nil {
		return &model.LoginResult{
			Success: false,
			Message: "invalid phone number or password",
		}, nil
	}

	sessionID := uuid.New()
	refresh, err := auth.IssueRefreshToken(auth.JWTRefreshSecret(), creds.ID, sessionID, auth.RefreshTokenTTL)
	if err != nil {
		return nil, fmt.Errorf("issue refresh token: %w", err)
	}
	if err := db.CreateSession(ctx, r.Pool, sessionID, creds.ID, auth.HashToken(refresh), time.Now().Add(auth.RefreshTokenTTL)); err != nil {
		return nil, fmt.Errorf("create session: %w", err)
	}
	access, err := auth.IssueAccessToken(auth.JWTSecret(), creds.ID, sessionID, auth.AccessTokenTTL)
	if err != nil {
		return nil, fmt.Errorf("issue access token: %w", err)
	}

	r.SMSQueue.Enqueue(types.SMSPayload{
		PhoneNumbers: []string{normalized},
		Message:      loginAccessAlert,
	}, "")
	r.clearAuth(normalized)

	return &model.LoginResult{
		Success:      true,
		Message:      "logged in; a text alert was sent to your phone",
		User:         toModelUser(&creds.UserRow),
		AccessToken:  &access,
		RefreshToken: &refresh,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.RefreshResult, error) {
	claims, err := auth.ParseToken(auth.JWTRefreshSecret(), token)
	if err != nil || !auth.IsRefresh(claims) {
		return &model.RefreshResult{
			Success: false,
			Message: "invalid or expired session",
		}, nil
	}

	userID, err := claims.UserID()
	if err != nil {
		return &model.RefreshResult{Success: false, Message: "invalid or expired session"}, nil
	}
	sessionID, err := claims.SessionID()
	if err != nil {
		return &model.RefreshResult{Success: false, Message: "invalid or expired session"}, nil
	}

	user, err := db.AuthenticateSession(ctx, r.Pool, sessionID, auth.HashToken(token))
	if err != nil {
		if errors.Is(err, db.ErrInvalidSession) {
			return &model.RefreshResult{Success: false, Message: "invalid or expired session"}, nil
		}
		return nil, fmt.Errorf("authenticate refresh session: %w", err)
	}
	if user.ID != userID {
		return &model.RefreshResult{Success: false, Message: "invalid or expired session"}, nil
	}

	rotated, err := auth.IssueRefreshToken(auth.JWTRefreshSecret(), userID, sessionID, auth.RefreshTokenTTL)
	if err != nil {
		return nil, fmt.Errorf("issue refresh token: %w", err)
	}
	if err := db.RotateSession(ctx, r.Pool, sessionID, auth.HashToken(rotated)); err != nil {
		if errors.Is(err, db.ErrInvalidSession) {
			return &model.RefreshResult{Success: false, Message: "invalid or expired session"}, nil
		}
		return nil, fmt.Errorf("rotate session: %w", err)
	}
	access, err := auth.IssueAccessToken(auth.JWTSecret(), userID, sessionID, auth.AccessTokenTTL)
	if err != nil {
		return nil, fmt.Errorf("issue access token: %w", err)
	}

	return &model.RefreshResult{
		Success:      true,
		Message:      "session refreshed",
		User:         toModelUser(user),
		AccessToken:  &access,
		RefreshToken: &rotated,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	req := auth.Request(ctx)
	if req == nil {
		return false, nil
	}
	claims, err := auth.ParseToken(auth.JWTSecret(), auth.BearerToken(req))
	if err != nil || !auth.IsAccess(claims) {
		return false, nil
	}
	sessionID, err := claims.SessionID()
	if err != nil {
		return false, nil
	}
	if err := db.RevokeSession(ctx, r.Pool, sessionID); err != nil {
		return false, fmt.Errorf("revoke session: %w", err)
	}
	return true, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, phone string) (*model.OTPResult, error) {
	normalized, err := validator.NormalizePhone(phone)
	if err != nil {
		return nil, err
	}
	if err := r.guardAuth(ctx, normalized); err != nil {
		return nil, err
	}

	registered, err := db.PhoneRegistered(ctx, r.Pool, normalized)
	if err != nil {
		return nil, fmt.Errorf("check phone registered: %w", err)
	}
	if !registered {
		return &model.OTPResult{
			Success: false,
			Message: "no account found for this phone number",
		}, nil
	}

	lastOTP, ok, err := db.LatestOTPTime(ctx, r.Pool, normalized, otpPurposePasswordReset)
	if err == nil && ok && time.Since(lastOTP) < otp.ResendMinPeriod {
		retryAfter := int(time.Until(lastOTP.Add(otp.ResendMinPeriod)).Seconds())
		if retryAfter < 1 {
			retryAfter = 1
		}
		return &model.OTPResult{
			Success:           false,
			Message:           "please wait before requesting another code",
			RetryAfterSeconds: int32Ptr(int32(retryAfter)),
		}, nil
	}

	code, codeHash, err := otp.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate otp: %w", err)
	}
	expiresAt := time.Now().Add(otp.DefaultTTL)
	if _, err := db.RequestOTP(ctx, r.Pool, normalized, otpPurposePasswordReset, codeHash, expiresAt); err != nil {
		return nil, fmt.Errorf("store otp: %w", err)
	}

	if !r.SMSQueue.Enqueue(types.SMSPayload{
		PhoneNumbers: []string{normalized},
		Message:      otp.Message(code, otp.DefaultTTL),
	}, "") {
		return &model.OTPResult{
			Success: false,
			Message: "temporarily unable to send the verification code, please try again",
		}, nil
	}

	return &model.OTPResult{
		Success:          true,
		Message:          "verification code sent",
		ExpiresInSeconds: int32Ptr(int32(otp.DefaultTTL.Seconds())),
	}, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, phone string, code string, password string, confirmPassword string) (*model.ResetPasswordResult, error) {
	normalized, err := validator.NormalizePhone(phone)
	if err != nil {
		return nil, err
	}
	if err := r.guardAuth(ctx, normalized); err != nil {
		return nil, err
	}

	if err := validator.ValidatePassword(password); err != nil {
		return nil, err
	}
	if err := validator.ValidatePasswordConfirmation(password, confirmPassword); err != nil {
		return nil, err
	}

	valid, reason, err := db.VerifyOTP(ctx, r.Pool, normalized, otpPurposePasswordReset, code)
	if err != nil {
		return nil, fmt.Errorf("verify otp: %w", err)
	}
	if !valid {
		return &model.ResetPasswordResult{
			Success: false,
			Message: otpFailureMessage(reason),
		}, nil
	}

	passwordHash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("hash password: %w", err)
	}
	if err := db.SetPassword(ctx, r.Pool, normalized, string(passwordHash)); err != nil {
		return nil, fmt.Errorf("set password: %w", err)
	}

	return &model.ResetPasswordResult{
		Success: true,
		Message: "password updated; please log in again",
	}, nil
}

// InviteToTeam is the resolver for the inviteToTeam field.
func (r *mutationResolver) InviteToTeam(ctx context.Context, phone string, role model.Role) (*model.InviteResult, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return nil, err
	}

	normalized, err := validator.NormalizePhone(phone)
	if err != nil {
		return nil, err
	}
	if normalized == user.Phone {
		return &model.InviteResult{
			Success: false,
			Message: "you cannot invite yourself",
		}, nil
	}

	team, err := db.EnsurePersonalTeam(ctx, r.Pool, user.ID)
	if err != nil {
		return nil, fmt.Errorf("load team: %w", err)
	}

	invite, err := db.InviteMember(ctx, r.Pool, team.ID, normalized, toDBRole(role), user.ID)
	if err != nil {
		switch {
		case errors.Is(err, db.ErrSelfInvite):
			return &model.InviteResult{Success: false, Message: err.Error()}, nil
		case errors.Is(err, db.ErrAlreadyInvited):
			return &model.InviteResult{Success: false, Message: err.Error()}, nil
		case errors.Is(err, db.ErrAlreadyMember):
			return &model.InviteResult{Success: false, Message: "this person is already a member of this team", AlreadyMember: true}, nil
		default:
			return nil, fmt.Errorf("invite member: %w", err)
		}
	}

	registered, err := db.PhoneRegistered(ctx, r.Pool, normalized)
	if err != nil {
		return nil, fmt.Errorf("check invitee registered: %w", err)
	}

	r.SMSQueue.Enqueue(types.SMSPayload{
		PhoneNumbers: []string{normalized},
		Message: inviteSMSFor(
			fmt.Sprintf("%s %s", user.FirstName, user.Surname),
			team.Name,
			registered,
		),
	}, "")

	invite.TeamName = team.Name
	invite.TeamID = team.ID
	invite.Status = "pending"
	modelInvite, err := toModelInvite(invite, user)
	if err != nil {
		return nil, err
	}

	return &model.InviteResult{
		Success:           true,
		Message:           "invitation sent",
		Invite:            modelInvite,
		InviteeRegistered: registered,
	}, nil
}

// AcceptInvite is the resolver for the acceptInvite field.
func (r *mutationResolver) AcceptInvite(ctx context.Context, inviteID uuid.UUID) (*model.AcceptInviteResult, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return nil, err
	}

	team, _, err := db.AcceptInvite(ctx, r.Pool, inviteID, user.ID)
	if err != nil {
		switch {
		case errors.Is(err, db.ErrNoPendingInvite):
			return &model.AcceptInviteResult{Success: false, Message: err.Error()}, nil
		case errors.Is(err, db.ErrInviteExpired):
			return &model.AcceptInviteResult{Success: false, Message: err.Error()}, nil
		case errors.Is(err, db.ErrInviteNotForYou):
			return &model.AcceptInviteResult{Success: false, Message: err.Error()}, nil
		case errors.Is(err, db.ErrAlreadyMember):
			return &model.AcceptInviteResult{Success: false, Message: err.Error()}, nil
		case errors.Is(err, db.ErrInviteInvalid):
			return &model.AcceptInviteResult{Success: false, Message: "this invite no longer exists"}, nil
		default:
			return nil, fmt.Errorf("accept invite: %w", err)
		}
	}

	teamView, err := r.buildTeam(ctx, team.ID, user.ID)
	if err != nil {
		return nil, err
	}
	return &model.AcceptInviteResult{
		Success: true,
		Message: "you joined the workspace",
		Team:    teamView,
	}, nil
}

// RevokeInvite is the resolver for the revokeInvite field.
func (r *mutationResolver) RevokeInvite(ctx context.Context, inviteID uuid.UUID) (bool, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return false, err
	}
	team, err := db.EnsurePersonalTeam(ctx, r.Pool, user.ID)
	if err != nil {
		return false, fmt.Errorf("load team: %w", err)
	}
	role, err := db.MemberRole(ctx, r.Pool, team.ID, user.ID)
	if err != nil {
		if errors.Is(err, db.ErrNotTeamMember) {
			return false, nil
		}
		return false, err
	}
	if role != "admin" {
		return false, nil
	}
	revoked, err := db.RevokeInvite(ctx, r.Pool, inviteID, user.ID)
	if err != nil {
		return false, fmt.Errorf("revoke invite: %w", err)
	}
	return revoked, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	req := auth.Request(ctx)
	if req == nil {
		return nil, errNotAuthenticated
	}
	claims, err := auth.ParseToken(auth.JWTSecret(), auth.BearerToken(req))
	if err != nil || !auth.IsAccess(claims) {
		return nil, errNotAuthenticated
	}
	userID, err := claims.UserID()
	if err != nil {
		return nil, errNotAuthenticated
	}
	sessionID, err := claims.SessionID()
	if err != nil {
		return nil, errNotAuthenticated
	}
	user, err := db.SessionUser(ctx, r.Pool, sessionID)
	if err != nil {
		if errors.Is(err, db.ErrInvalidSession) {
			return nil, errNotAuthenticated
		}
		return nil, fmt.Errorf("load session: %w", err)
	}
	if user.ID != userID {
		return nil, errNotAuthenticated
	}
	return toModelUser(user), nil
}

// MyTeam is the resolver for the myTeam field.
func (r *queryResolver) MyTeam(ctx context.Context) (*model.Team, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return nil, err
	}
	team, err := db.EnsurePersonalTeam(ctx, r.Pool, user.ID)
	if err != nil {
		return nil, fmt.Errorf("load team: %w", err)
	}
	return r.buildTeam(ctx, team.ID, user.ID)
}

// MyInvites is the resolver for the myInvites field.
func (r *queryResolver) MyInvites(ctx context.Context) ([]*model.Invite, error) {
	user, err := r.currentUser(ctx)
	if err != nil {
		return nil, err
	}
	inviteRows, err := db.PendingInvitesForPhone(ctx, r.Pool, user.Phone)
	if err != nil {
		return nil, fmt.Errorf("load invites: %w", err)
	}
	invites := make([]*model.Invite, 0, len(inviteRows))
	for i := range inviteRows {
		inviter := &types.UserRow{
			ID:        inviteRows[i].InvitedBy,
			FirstName: inviteRows[i].InvitedByFirstName,
			Surname:   inviteRows[i].InvitedBySurname,
		}
		invite, err := toModelInvite(&inviteRows[i], inviter)
		if err != nil {
			return nil, err
		}
		invites = append(invites, invite)
	}
	return invites, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
